steps:

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - '--filename=k8s-config-files/deployment.yaml'
    - '--image=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_VERSION}'
    - '--location=${_CLOUDSDK_COMPUTE_ZONE}'
    - '--cluster=${_CLOUDSDK_CONTAINER_CLUSTER}'

  
  # - name: "gcr.io/cloud-builders/gke-deploy"
  #   args:
  #   - apply
  #   - '--filename=k8s-config-files'
  #   - '--location=${_CLOUDSDK_COMPUTE_ZONE}'
  #   - '--cluster=${_CLOUDSDK_CONTAINER_CLUSTER}'


substitutions:
  _PROJECT_ID: 'gcp-devops-420503'
  _IMAGE_NAME: 'gke-cicd'
  _CLOUDSDK_COMPUTE_ZONE: 'us-east1-b'
  _CLOUDSDK_CONTAINER_CLUSTER: 'cicd-cluster'
  # _VERSION: '3.0'