name: 01-Building_Blocks
on: workflow_dispatch

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
        - name: Greetings
          run: echo "Hello World"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Succeed
              run: |
                echo "I will succeed"
                exit 0
            - name: Goodbye
              run: echo "Good bye"
    