name: 01-Building_Blocks
on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
        - name: Greetings
          run: echo "Hello I Love You Raji"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Succeed
              run: |
                echo "I will succeed"
                exit 0
            - name: Goodbye
              run: echo "Good Night Baby ma"
    