name: 01-Building_Blocks
on: 
  pull_request_review:
  workflow_dispatch:
  
permissions: write-all

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        if: github.event.review.state == 'APPROVED'
        steps:
        - name: Greetings
          run: echo "Hello World"

    echo-goodbye:
        runs-on: ubuntu-latest
        if: github.event.review.state == 'APPROVED'
        steps:
            - name: Succeed
              run: |
                echo "I will succeed"
                exit 0
            - name: Goodbye
              run: echo "Good bye"
    