name: 02-Workflow-Events
on: push

jobs:
    echo-trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "Event Name : ${{ github.event_name }}"

