name: 04-Actions-Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-actions-github/my-app
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test
