name: 04-Actions-Workflow
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-actions-github/my-app
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
     # working-directory: 04-actions-github/my-app - We can directly mention this in defaults in job name object to ignore replicate the same values in run object.
    - name: Test
      run: npm test
    #  working-directory: 04-actions-github/my-app