name: 06-Contexts
run-name: 06-Contexts
on: 
   - push
   - workflow_dispatch


# Actor used in the first step give the output of the author of the pipeline
jobs:
    print-context:
        runs-on: ubuntu-latest
        steps:
            - name: Printing Contexts
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run Id: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"

            - name: Printing the variable
              run: |
                echo "Print My Variable: ${{ vars.MY_VAR }}"
