name: 09-Functions
on: 
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            
            - name: Print PR Title
              run: |
                echo "PR Title: ${{ github.event.pull_request.title }}"
            
            - name: Print the PR Labels
              run: |
                echo "PR Labels: "
                cat << EOF
                ${{ toJson(github.event.pull_request.labels)}}
                EOF
            
            - name: Bug Fix
              if: ${{ !cancelled() && contains( github.event.pull_request.title, 'fix' )}}
              run: |
                echo "This is a bug fix"
                
            - name: Sleep for 10 seconds
              run: sleep 10
            - name: Failed Step
              run: |
                exit 1
            - name: I will skip
              if: ${{ success() }}
              run: |
                echo "I will execute if previous step success"
            - name: I will execute
              if: ${{ failure() }}
              run: |
                echo "I will execute if any previous step fail."
            - name: I will execute
              if: ${{ !cancelled() }}
              run: |
                echo "I will always execute"
            - name: I will execute if cancel
              if: ${{ cancelled() }}
              run: |
                echo "I will execute if the workflow cancelled"

