name: 12-Outputs
run-name: 12-Outputs
on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - fail
                default: fail
                description: Select Success or Fail
jobs:
    build-job:
        runs-on: ubuntu-latest
        outputs:
            output-build-status: ${{ steps.build-id.outputs.status }}
        steps:
            - name: Print GITHUB_OUTPUTS
              run: echo $GITHUB_OUTPUTS

            - name: Build
              id: build-id
              run: |
                echo "status=${{inputs.build-status}}" >> $GITHUB_OUTPUTS
    deploy-job:
        runs-on: ubuntu-latest
        needs:
            - build-job
        if: ${{ needs.build-job.outputs.output-build-status == 'success'}}
        steps:
            - name: Deploy
              run: echo "Deploying........."