name: 12-Outputs
run-name: 12-Outputs
on:
    workflow_dispatch:
        inputs:
            build-status:
                type: choice
                options:
                    - success
                    - fail
                default: success
                description: Select Success or Fail
jobs:
    build-job:
        runs-on: ubuntu-latest
        outputs:
            output-build-status: ${{ steps.build-id.outputs.status }}
            output-one: ${{ steps.build-id.outputs.output1 }}
            output-two: ${{ steps.build-id.outputs. output2 }}
        steps:
            - name: Print GITHUB_OUTPUT
              run: echo $GITHUB_OUTPUT

            - name: Build
              id: build-id
              run: |
                echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"
                echo "output1=value1" >> $GITHUB_OUTPUT
                echo "output2=value2" >> $GITHUB_OUTPUT
                echo "mistake=true" > "$GITHUB_OUTPUT"
                
    deploy-job:
        runs-on: ubuntu-latest
        needs:
            - build-job
        if: ${{ needs.build-job.outputs.output-build-status == 'success'}}
        steps:
            - name: Deploy
              run: echo "Deploying........."
            - name: Print Outputs
              run: |
                echo "Output-one value: ${{ needs.build-job.outputs.output-one }}"