name: 14-Working-With-Artifacts
run-name: 14-Working-With-Artifacts
on:
    workflow_dispatch:

env:
  build-artifact-key: app-${{ github.sha }}
  test-coverage-key: test-coverage-${{ github.sha }}

jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 13-caching/react-app
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
            
            - name: Download Cached Dependency
              uses: actions/cache@v3
              id: cache
              with:
                path: 14-caching/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
            
            - name: Install Dependencies
              if: ${{ steps.cache.outputs.cache-hit != 'true'}}
              run: npm ci

            - name: Run Test
              run: npm run test -- --coverage

            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                name: test-coverage-${{ github.sha }}
                path: 13-caching/react-app/coverage
            
            - name: Run Build
              run: npm run build
            
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: app-${{ github.sha }}
                path: 13-caching/react-app/build
            
    deploy:
        runs-on: ubuntu-latest
        needs: 
            - test-build
        steps:
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: app-${{ github.sha }}
                path: build
