name: Deploy to GCP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        version: 'latest'
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Authenticate to GCP
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${GCP_SERVICE_ACCOUNT_KEY}" > ${HOME}/gcp-key.json
        gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
        mkdir -p ~/.kube
        echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> ~/.bashrc
        source ~/.bashrc
        
    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials multi-cluster --zone us-central1-c --project k8s-project-425213

    - name: List Kubernetes Pods
      run: |
        kubectl get pods

    - name: Deploy to GCP
      run: |
        # Your deployment commands here, e.g.:
        # gcloud app deploy
        # gcloud functions deploy
        # gcloud builds submit
